name = "gold-price-service"
main = "src/index.ts"
compatibility_date = "2026-02-07"

[observability]
enabled = true

[[kv_namespaces]]
binding = "TOKENS_KV"
id = "2b7fe157922a44198025cc6fd6a9e288"

[vars]
QUOTE_CACHE_TTL_SECONDS = "120"
FX_CACHE_TTL_SECONDS = "21600"
